spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/media_tracker_pg
    username: user
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
    jooq:
      sql-dialect: POSTGRES
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: media_schema


logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG
    org.jooq.tools.JDBCUtils: DEBUG
    com.example.mediatracker.client.KinopoiskClient: DEBUG
    feign.Logger: DEBUG

hosts:
  kinopoisk:
    url: https://kinopoiskapiunofficial.tech/
    api-key: ${KINOPOISK_API_KEY}