spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/media_tracker_pg
    username: user
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: media_schema

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration:
    access-min: 30
    refresh-days: 7

logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG
    org.jooq.tools.JDBCUtils: DEBUG

hosts:
  kinopoisk:
    url: https://kinopoiskapiunofficial.tech
    api-key: ${KINOPOISK_API_KEY}